# Generated by Django 3.0.7 on 2020-08-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
